### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by walialu** [d0c-s4vage/lookatme#92]
**Describe the Feature Request**
Could you add image support? 

**Example Markdown**

```markdown
![](https://about.walialu.com/pool.jpg)
```
![](https://about.walialu.com/pool.jpg)

**Comment by d0c-s4vage** [comment]
Hahaha nice picture :^)

I've experimented a lot with this. There are two ways to get image support into urwid:

* depend on specific terminals that support full image rendering in the terminal. See this stack overflow question about this: https://askubuntu.com/questions/97542/how-do-i-make-my-terminal-display-graphical-pictures
  * This has been sort-of hit-or miss for me. At least in the environments that I have attempted this in (emulator kitty, for example), the terminal emulator doesn't fully support all of the features that urwid itself needs, even though it can render images. So I've gotten images to work, but then the basic slide functionality breaks.

* Render pixelated images using colored unicode characters to the terminal
  * I've tested this out - it definitely works! I tried this a few ways - using native python code to do the image processing and rendering or to wrap a tool such as [tiv](https://github.com/stefanhaustein/TerminalImageViewer). Tiv was definitely faster than any python image processing that I could put together.

In general I try to keep the lookatme base install pretty lightweight - adding external dependencies such as a special terminal emulator, or dependencies on another tool such as `tiv`, are reasons where I would create a contrib extension to lookatme instead of adding it into the core project.

That being said, this is also a feature that I've wanted for a long time. Maybe it's about time I figure it out. A robust extension that falls back to`tiv` if a supported emulator is not found would be really nice.

**Comment by d0c-s4vage** [comment]
Here's a gif of the python-based rendering that I worked on for a while:

![lookatme_termage](https://user-images.githubusercontent.com/5090146/93669722-00bb7d80-fa4b-11ea-95bc-8986b0b10671.gif)

**Comment by walialu** [comment]
This looks awesome!

**Comment by fischercer** [comment]
Just out of curiosity, did your also check Überzug https://github.com/seebye/ueberzug as this is not mentioned in the Stack overflow link you posted. I think it still would be a great addition to have nice image render support even if it would display full-size/full slide images. 

I use it with alacritty and it works pretty well for me, but I haven‘t used it with kitty though.

**Comment by walialu** [comment]
This looks really promising: https://github.com/seebye/urwid-ueberzogen

**Comment by d0c-s4vage** [comment]
No, I did not know about ueberzug! Haha I love that the urwid plugin is correct German :^)

I'll check these out. The good thing about having the plugin system is that you can have multiple plugins that each provide their own way of rendering markdown images :^) An ueberzug/ueberzogen image plugin would be great

**Comment by d0c-s4vage** [comment]
![lookatme_image_test](https://user-images.githubusercontent.com/5090146/94020442-c3ffc700-fd67-11ea-9c5f-efdb3527db2a.gif)

This was with urwid_ueberzogen! Has a few things that will need to be sorted out:

* padding values are not taken into account when positioning the image
* image isn't cropped as it is scrolled
* image transparency doesn't seem to work
* gifs don't work in ueberzug - https://github.com/seebye/ueberzug/issues/55

These may end up being bugs in the test extension I wrote, or maybe bugs in urwid_ueberzogen.

Either way, it's looking promising :^)

**Comment by d0c-s4vage** [comment]
Follow development/beta testing of the lookatme.contrib.image_ueberzug plugin here: https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug/issues/1

**Comment by d0c-s4vage** [comment]
Considering this taken care of now - https://github.com/d0c-s4vage/lookatme.contrib.image_ueberzug is live!
